# Generated by Django 5.2.13 on 2026-06-11 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_profile_email_for_receipt_alter_cart_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город доставки'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category', verbose_name='Любимая категория'),
        ),
    ]
